name: destroy
on:
  workflow_dispatch:
    inputs:
      TFDestroy:
        description: 'Destroy TF Automatically (false/true) - Default: true'
        required: true
        default: 'true'
env:
  BACKEND_BUCKET: mystatedemobucket
  BACKEND_REGION: "eu-west-1"
  TF_VAR_prefix: dev
jobs:
  Terraform-destroy:   
    runs-on: codebuild-codebuild-project-${{ github.run_id }}-${{ github.run_attempt }}
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.1
    - name: Terraform Init
      id: init
      run: terraform init -backend-config="key=$TF_VAR_prefix" -backend-config="region=$BACKEND_REGION" -backend-config="bucket=$BACKEND_BUCKET"
      
    - name: Terraform destroy
      id: apply
      run: terraform apply -destroy -auto-approve 
