name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-codebuild-project-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
